general {
    lock_cmd = pidof hyprlock || hyprlock           # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session        # lock before suspend.
    after_sleep_cmd = niri msg output eDP-1 on      # to avoid having to press a key twice to turn on the display.
}

# turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
listener {
    timeout = 1                                                                            # seconds
    on-timeout = $HOME/.config/niri/scripts/backlight-dim.sh 5 'chromeos\:\:kbd_backlight'          # turn off keyboard backlight.
    on-resume  = $HOME/.config/niri/scripts/backlight-dim.sh restore 'chromeos\:\:kbd_backlight'    # turn on keyboard backlight.
}

listener {
    timeout = 4                                                                            # seconds
    on-timeout = hyprlock -c $HOME/.config/niri/hyprlock.conf                               # lock screen when timeout has passed
}

listener {
    timeout = 6                                                                            # seconds
    on-timeout = $HOME/.config/niri/scripts/backlight-dim.sh 5 'amdgpu_bl1'                         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume  = $HOME/.config/niri/scripts/backlight-dim.sh restore 'amdgpu_bl1'                   # monitor backlight restore.
}

listener {
    timeout = 9                                    # seconds
    on-timeout = niri msg output eDP-1 off          # screen off when timeout has passed
    on-resume  = niri msg output eDP-1 on           # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 180                                   # seconds
    on-timeout = systemctl suspend                  # suspend pc
}
