[window]
padding = { x = 0, y = 0 }
opacity = 0.8

[font]
normal = { family = "NotoSansM Nerd Font Mono" }
## bold = { style = "Bold" }
size = 14.0

[cursor]
style = { shape = "Block", blinking = "On" }

[colors]
 [colors.primary]
 background = "#000000"
 foreground = "#ffffff"

 [colors.selection]
 text = "#000000"
 background = "#ffffff"
